name: CubeConomy
main: de.iani.cubeConomy.CubeConomy
version: 1.1.0
description: CubeConomy
authors:
  - Brokkonaut
depend: [PlayerUUIDCache]
softdepend: [Vault]
api-version: 1.13

commands:
  money:
    description: Money
    usage: /<command>
  pay:
    description: Pay Money
    usage: /<command>